### ISSUE TITLE
support for amd gpus

### ISSUE THREAD

**Issue by tristan-k** [karli-sjoberg/gswitch#1]
Is there or will there be support for amd gpus? I'm running a aorus gaming box rx580 8gb with a hp spectre x360 13 (i5-8250U). I would glady use your scripts to swtich between intels uhd 620 and amds rx580.

``` 
$ lspci | grep VGA 
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
00:13.0 Non-VGA unclassified device: Intel Corporation Sunrise Point-LP Integrated Sensor Hub (rev 21)
08:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] (rev e7)
$ xrandr --listproviders 
Providers: number : 2
Provider 0: id: 0x71 cap: 0x9, Source Output, Sink Offload crtcs: 3 outputs: 5 associated providers: 1 name:modesetting
Provider 1: id: 0x49 cap: 0x6, Sink Output, Source Offload crtcs: 6 outputs: 4 associated providers: 1 name:Radeon RX 580 Series @ pci:0000:08:00.0
$  DRI_PRIME=1 glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.25.0, 4.17.19-041719-generic, LLVM 7.0.0)
$ DRI_PRIME=0 glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)
```

**Comment by karli-sjoberg** [comment]
Yeay, my first "Issue"! :)

Indeed there is support for AMD GPUs, you only have to change the driver to "amdgpu" instead of "nvidia" in the xorg.conf.egpu file and remember to change the "BusID" accordingly. That's it!

How's your performance running a game or something through PRIME? Like if you'd "DRI_PRIME=1 game" is the performance better than the Intel iGPU? I'm curious because I could never get PRIME working, it always selects my Quadro M1000M dGPU.

I know another dude has tried and had bad performance, but with a Matebook X Pro, Akitio Node 3 and RX580. The difference between him and you is that the Matebook only has 2xPCIe TB3, so I looked up your laptop and it seems to be a full 4x PCIe Thunderbolt 3 port in there so you shouldn't have any problems, but I'll keep the issue open until you have tested it.

If you do have bad performance, it would seem AMD support is still not quite there yet in Linux. Maybe a newer kernel fixes that, I don't know, but I'm really hoping for AMD so I can finally ditch NVIDIA :)

What distro are you on?
