### ISSUE TITLE
Enable internal switching to xorg.conf.internal

### ISSUE THREAD

**Issue by shervinsahba** [karli-sjoberg/gswitch#11]
I have a `xorg.conf.internal` for my internal Intel graphics unit. I find it useful for `sudo gswitch internal` to set `xorg.conf` to this instead of removing `xorg.conf`. Here are the changes I implemented. If this is useful, I can add a PR. Thanks for making this utlity Karli - we appreciate it!

(I should mention that I also added the constant `XORG_DIR="/etc/X11/xorg.conf.d"` to the top of `gswitch` and `Makefile`, since this is where Manjaro prefers to file its xorg configs. Maybe consider incorporating this variable too with a default of `/etc/X11`.)

---

**gswitch:**

In `switch_internal()`, I changed
```
    rm -f ${XORG_DIR}/xorg.conf
```
to
```
    rm -f ${XORG_DIR}/xorg.conf
    if [ -e ${XORG_DIR}/xorg.conf.internal ];  then
      ln -s ${XORG_DIR}/xorg.conf.internal ${XORG_DIR}/xorg.conf
    fi
```

Also, in `switch_egpu()`, I changed
```
    ln -s ${XORG_DIR}/xorg.conf.egpu ${XORG_DIR}/xorg.conf
```
to 
```
    rm -f ${XORG_DIR}/xorg.conf 
ln -s ${XORG_DIR}/xorg.conf.egpu ${XORG_DIR}/xorg.conf
```

---

The makefile was updated to reflect these changes and help with cleanup.

**makefile:**
```
XORG_DIR=${DESTDIR}/etc/X11/xorg.conf.d

all:

install:
	mkdir -p ${DESTDIR}/usr/bin
	cp gswitch ${DESTDIR}/usr/bin/gswitch
	chmod +x ${DESTDIR}/usr/bin/gswitch
	mkdir -p ${DESTDIR}/usr/share/gswitch
	if [ -e ${XORG_DIR}/xorg.conf ]; then \
		mv ${XORG_DIR}/xorg.conf ${XORG_DIR}/xorg.conf.internal; \
		ln -s ${XORG_DIR}/xorg.conf.internal ${XORG_DIR}/xorg.conf; \
	fi
	cp xorg.conf.egpu ${DESTDIR}/usr/share/gswitch/xorg.conf.egpu
	mkdir -p ${DESTDIR}/etc/systemd/system
	cp gswitch.service ${DESTDIR}/etc/systemd/system/gswitch.service
	systemctl daemon-reload

uninstall:
	rm -f ${DESTDIR}/etc/systemd/system/gswitch.service
	rm -f ${XORG_DIR}/xorg.conf.egpu
	if [ -e ${XORG_DIR}/xorg.conf.internal ]; then \
		mv ${XORG_DIR}/xorg.conf.internal ${XORG_DIR}/xorg.conf; \
	fi	
	rm -rf ${DESTDIR}/usr/share/gswitch
	rm -f ${DESTDIR}/usr/bin/gswitch
	systemctl daemon-reload
```

**Comment by karli-sjoberg** [comment]
Hey man!

The XORG_DIR variable seems like a no-brainer, I haven't had any need for it since it was originally written only for Ubuntu and derivatives in mind, but I don't see any problems with that, on the contrary, I welcome it 😊

The xorg.conf.internal though requires some thinking first. Does everyone in Manjaro have to have their own config to begin with?

The reason I ask is because in Ubuntu, their is no xorg.conf at all. It just uses scripts and xrandr to "figure it out" automagically, which then raises the question, how should the internal config then look like for everyone else?

/K

**Comment by shervinsahba** [comment]
Hey! My approach was to first check if a user has a `xorg.conf` first. If they do, then it creates the `xorg.conf.internal` for switching. If they don't, then it should run like your original. 

One concern this addresses is that that `switch_internal()` currently clobbers a user's `xorg.conf`. While this would be the user's fault if they naively run the program, the suggested code could prevent that mishap.

---

You raise a good question about Manjaro, though. From what I understand, Arch-based systems don't necessarily require a `xorg.conf`, but for [Intel graphics may require a conf file](https://wiki.archlinux.org/index.php/Intel_graphics#Xorg_configuration). This was true for my system, and I had the `20-intel.conf` mentioned in that link acting as my `xorg.conf`. 

I had to manage this file in order for `gswitch` to work. First, I renamed the file to `xorg.conf`, since I imagined this could match a general use scenario. Then I let `gswitch` map it to `xorg.conf.internal` so I could switch back to it for internal graphics.

**Comment by karli-sjoberg** [comment]
So waaay later I looked over the open issues and saw this. I apologize for forgetting about this! But it turns out that this worked itself out. The code is now written like this on any untested distribution:

```
    # Untested OS distribution
    # Hoping the path works the all the same
    XORG_CONF_DIR="/etc/X11/xorg.conf.d"
    if [ ! -d "${XORG_CONF_DIR}" ]; then
      mkdir -p "${XORG_CONF_DIR}"
    fi
    EGPU_TEMPLATE="${XORG_CONF_DIR}/xorg.conf.egpu"
    XORG_CONFIG="${XORG_CONF_DIR}/99-gswitch-egpu.conf"
```
So the file name `xorg.conf` is no longer used anyway. Thought it might be good to at least mention that.
