### ISSUE TITLE
[feature request] Add dGPU support

### ISSUE THREAD

**Issue by TechKnowCase** [karli-sjoberg/gswitch#14]
Hey!

I would like to know if it's possible to add dGPU support to gswitch. That way, I can quicky change from iGPU to eGPU for gaming/work at home and from iGPU to dGPU for gaming/work on the go.

Thank you

**Comment by karli-sjoberg** [comment]
I've had that thought as well but I can't imagine how that would best be implemented. The biggest challenge is how the script should decide which GPU (d/e) is "the best"? I mean, given a list of GPUs, how should the script "rate" them, I have no idea!

The way I've dealt with it is to put the computer in "Performance mode" in "nvidia-settings" when I want to use the eGPU and that makes "gswitch" remove the eGPU when you're away from home, falling back to the dGPU. When you want extended battery life on the go, just put it in "Power Saving Mode" instead.

**Comment by TechKnowCase** [comment]
Hey!

Why would the script need to guess which GPU is which? You could use "gswitch setup" to ask the user if they have a dgpu, if they do, what's the ID. 

From my perspective, if I go though the trouble to buying a eGPU, it's because my dGPU is not powerfull enough, if that answer your question.

**Comment by karli-sjoberg** [comment]
Maybe I'm stupid but I'm closing this issue since the feature requested is already implemented. There's nothing stopping you from running 'gswitch setup' and entering your dGPU PCI ID when asked for it (no idea how well it works though). If I've misunderstood something, open a new issue with a clearer description of the feature request.
